const categories = [
  {
    id: "boats",
    nameAr: "المركبات",
    nameEn: "Vehicles",
    photos: [
      { url: "/boats/boat-01.jpg", title: "Boat 01", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-02.jpg", title: "Boat 02", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-03.jpg", title: "Boat 03", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-04.jpg", title: "Boat 04", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-05.jpg", title: "Boat 05", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-06.jpg", title: "Boat 06", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-07.jpg", title: "Boat 07", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-08.jpg", title: "Boat 08", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-09.jpg", title: "Boat 09", desc: "Boats photography", pos: "50% 50%" },
      { url: "/boats/boat-10.jpg", title: "Boat 10", desc: "Boats photography", pos: "50% 50%" },
    ],
  },
  {
    id: "portrait",
    nameAr: "الشخصية",
    nameEn: "Portrait",
    photos: [
      { url: "/portrait/portrait-01.jpg", title: "Portrait 01", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-02.jpg", title: "Portrait 02", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-03.jpg", title: "Portrait 03", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-04.jpg", title: "Portrait 04", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-05.jpg", title: "Portrait 05", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-06.jpg", title: "Portrait 06", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-07.jpg", title: "Portrait 07", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-08.jpg", title: "Portrait 08", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-09.jpg", title: "Portrait 09", desc: "Portrait photography", pos: "50% 30%" },
      { url: "/portrait/portrait-10.jpg", title: "Portrait 10", desc: "Portrait photography", pos: "50% 30%" },
    ],
  },
  {
    id: "architecture",
    nameAr: "المعماري",
    nameEn: "Architecture",
    photos: [
      { url: "/architecture/arch-01.jpg", title: "Arch 01", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-02.jpg", title: "Arch 02", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-03.jpg", title: "Arch 03", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-04.jpg", title: "Arch 04", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-05.jpg", title: "Arch 05", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-06.jpg", title: "Arch 06", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-07.jpg", title: "Arch 07", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-08.jpg", title: "Arch 08", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-09.jpg", title: "Arch 09", desc: "Architecture photography", pos: "50% 50%" },
      { url: "/architecture/arch-10.jpg", title: "Arch 10", desc: "Architecture photography", pos: "50% 50%" },
    ],
  },
  {
    id: "food",
    nameAr: "الاطعمة",
    nameEn: "Food",
    photos: [
      { url: "/food/food-01.jpg", title: "Food 01", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-02.jpg", title: "Food 02", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-03.jpg", title: "Food 03", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-04.jpg", title: "Food 04", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-05.jpg", title: "Food 05", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-06.jpg", title: "Food 06", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-07.jpg", title: "Food 07", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-08.jpg", title: "Food 08", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-09.jpg", title: "Food 09", desc: "Food photography", pos: "50% 50%" },
      { url: "/food/food-10.jpg", title: "Food 10", desc: "Food photography", pos: "50% 50%" },
    ],
  },
  {
    id: "products",
    nameAr: "المنتجات",
    nameEn: "Products",
    photos: [
      { url: "/products/product-01.jpg", title: "Product 01", desc: "Product photography", pos: "50% 30%" },
      { url: "/products/product-02.jpg", title: "Product 02", desc: "Product photography", pos: "50% 30%" },
      { url: "/products/product-03.jpg", title: "Product 03", desc: "Product photography", pos: "50% 30%" },
      { url: "/products/product-04.jpg", title: "Product 04", desc: "Product photography", pos: "50% 30%" },
      { url: "/products/product-05.jpg", title: "Product 05", desc: "Product photography", pos: "50% 50%" },
      { url: "/products/product-06.jpg", title: "Product 06", desc: "Product photography", pos: "50% 50%" },
      { url: "/products/product-07.jpg", title: "Product 07", desc: "Product photography", pos: "50% 50%" },
      { url: "/products/product-08.jpg", title: "Product 08", desc: "Product photography", pos: "50% 50%" },
      { url: "/products/product-09.jpg", title: "Product 09", desc: "Product photography", pos: "50% 50%" },
      { url: "/products/product-10.jpg", title: "Product 10", desc: "Product photography", pos: "50% 50%" },
    ],
  },
  {
    id: "astro",
    nameAr: "الفلكي",
    nameEn: "Astrophotography",
    photos: [
      { url: "/astro/astro-01.jpg", title: "Astro 01", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-02.jpg", title: "Astro 02", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-03.jpg", title: "Astro 03", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-04.jpg", title: "Astro 04", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-05.jpg", title: "Astro 05", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-06.jpg", title: "Astro 06", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-07.jpg", title: "Astro 07", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-08.jpg", title: "Astro 08", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-09.jpg", title: "Astro 09", desc: "Astrophotography", pos: "50% 50%" },
      { url: "/astro/astro-10.jpg", title: "Astro 10", desc: "Astrophotography", pos: "50% 50%" },
    ],
  },
];

export function getCategoryById(id) {
  return categories.find((c) => c.id === id);
}

export default categories;
